services:
  config-service:
    image: eclipse-temurin:21-jdk-alpine
    volumes:
      - ./config-service/build/libs/config-service-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8888/actuator/health"]
      interval: 3s
      timeout: 2s
      retries: 5

  dashboard-service:
    image: eclipse-temurin:21-jdk-alpine
    depends_on:
      config-service:
        condition: service_healthy
    volumes:
      - ./dashboard-service/build/libs/dashboard-service-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  order-service:
    image: eclipse-temurin:21-jdk-alpine
    depends_on:
      config-service:
        condition: service_healthy
    volumes:
      - ./order-service/build/libs/order-service-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  product-service:
    image: eclipse-temurin:21-jdk-alpine
    depends_on:
      config-service:
        condition: service_healthy
    volumes:
      - ./product-service/build/libs/product-service-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  user-service:
    image: eclipse-temurin:21-jdk-alpine
    depends_on:
      config-service:
        condition: service_healthy
    volumes:
      - ./user-service/build/libs/user-service-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  graphql-api-gateway:
    image: eclipse-temurin:21-jdk-alpine
    depends_on:
      config-service:
        condition: service_healthy
    volumes:
      - ./api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: product
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  postgres-order:
    image: postgres:15
    container_name: postgres-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: order
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgres-user-data:
  postgres-product-data:
  postgres-order-data: