filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - "/var/log/app/*.log"  # 모든 서비스의 로그를 모니터링
    fields:
      log_type: application
    fields_under_root: true
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'  # 날짜 형식으로 시작하는 로그 줄을 감지
      negate: true  # 날짜로 시작하지 않는 줄은 이전 줄과 합침
      match: after  # 날짜로 시작하는 줄이 나오기 전까지 이전 로그와 합침

output.logstash:
  hosts: ["logstash:5044"]