spring:
  application:
    name: api-gateway
  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI}"
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/

server:
  port: 8084