global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8084"]

  - job_name: "dashboard-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["dashboard-service:8080"]