spring:
  application:
    name: api-gateway
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  observations:
    http:
      server:
        requests:
          enabled: true # http request