spring:
  application:
    name: order-service
  r2dbc:
    url: r2dbc:postgresql://postgres-order:5432/orderdb
    username: order
    password: secret
    initialize: true
    initialization-mode: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://postgres-product:5432/orderdb
    user: order
    password: secret

server:
  port: 8081