spring:
  application:
    name: order-service
  r2dbc:
    url: r2dbc:postgresql://postgres-order:5432/orderdb
    username: order
    password: secret
    initialize: true
    initialization-mode: true

server:
  port: 8081