spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://postgres-order:5432/orderdb
    username: order
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081