spring:
  application:
    name: product-service
  r2dbc:
    url: r2dbc:postgresql://postgres-product:5432/productdb
    username: product
    password: secret
    initialize: true

server:
  port: 8082