spring:
  application:
    name: product-service
  r2dbc:
    url: r2dbc:postgresql://postgres-product:5432/productdb
    username: product
    password: secret
    initialize: true
    initialization-mode: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://postgres-product:5432/productdb
    username: product
    password: secret

server:
  port: 8082

logging:
  level:
    org.flywaydb: DEBUG