spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-product:5432/productdb
    username: product
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082