spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://postgres-user:5432/userdb
    username: user
    password: secret
    initialize: true
    initialization-mode: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://postgres-user:5432/user
    user: user
    password: secret

server:
  port: 8083