server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/reposy/msa-demo/
          searchPaths: configs
          default-label: main
